### ISSUE TITLE
Importing fails due to missing method in project

### ISSUE THREAD

**Issue by abelsromero** [robertpanzer/asciidoctorj-pdf#1]
When I try to import it, or just run some task in the shell the following error appears
```
* Where:
Script 'C:\home\bin\.babun\cygwin\home\asalgadr\temp\asciidoctorj-pdf\gradle\publish.gradle' line: 83

* What went wrong:
A problem occurred configuring project ':asciidoctorj-pdf'.
> Could not find method isDistribution() for arguments [] on project ':asciidoctorj-pdf' of type org.gradle.api.Project.
```

I think the project is missing the additional build logic in `asciidoctorj-distibution` or the build script here needs to be fixed. I really don't understand all details.

**Comment by robertpanzer** [comment]
Awesome, thanks @abelsromero 
No idea how it built locally on my machine with this error.
I even did a publishToMavenLocal.
